from __future__ import annotations

from ai_visibility.models import Business


SAMPLE_COMPETITORS: dict[tuple[str, str], list[Business]] = {
    ("Houston", "personal injury"): [
        Business("The Ammons Law Firm, LLP", "https://www.ammonslaw.com/"),
        Business("Bankston & Associates", "https://www.bankstonlaw.net/"),
        Business("Blizzard Law, PLLC", "https://www.blizzardlaw.com/"),
        Business("The Lanier Law Firm", "https://www.lanierlawfirm.com/"),
        Business("Arnold & Itkin LLP", "https://www.arnolditkin.com/"),
        Business("The Krist Law Firm, P.C.", "https://www.houstoninjurylawyer.com/"),
        Business("The Sher Law Firm, PLLC", "https://sher-law.com/"),
        Business("Sorey & Hoover, LLP", "https://soreylaw.com/"),
        Business("Sorrels Law", "https://www.sorrelslaw.com/"),
        Business("Baumgartner Law Firm", "https://baumgartnerlawyers.com/"),
        Business("Stephen Boutros, LTD.", "https://www.boutroslaw.com/"),
        Business("HURTINTEXAS.COM Law Firm", "https://www.hurtintexas.com/"),
        Business("Leo & Oginni Personal Injury Lawyers, PLLC", "https://www.helpishere.law/"),
        Business("Shariff Injury Lawyers", "https://www.shariffinjurylawyers.com/"),
        Business("Simon & O'Rourke Car Accident & Personal Injury Lawyers", "https://solawpc.com/"),
    ],
    ("New York", "itinerary"): [
        Business("Times Square", "https://www.timessquarenyc.org/"),
        Business("Central Park", "https://www.centralparknyc.org/"),
        Business("Statue of Liberty", "https://www.nps.gov/stli/index.htm"),
        Business("Empire State Building", "https://www.esbnyc.com/"),
        Business("Metropolitan Museum of Art", "https://www.metmuseum.org/"),
        Business("Brooklyn Bridge", "https://www.nyc.gov/site/brooklynbridge/index.page"),
        Business("One World Observatory", "https://www.oneworldobservatory.com/"),
        Business("9/11 Memorial & Museum", "https://www.911memorial.org/"),
        Business("Broadway", "https://www.broadway.com/"),
        Business("Fifth Avenue", "https://www.fifthavenueshops.com/"),
    ],
    ("Las Vegas", "itinerary"): [
        Business("Las Vegas Strip", "https://www.lasvegas.com/experience/las-vegas-strip/"),
        Business("Fremont Street Experience", "https://vegasexperience.com/"),
        Business("Bellagio Fountains", "https://bellagio.mgmresorts.com/en/entertainment/fountains-of-bellagio.html"),
        Business("High Roller Observation Wheel", "https://www.caesars.com/linq/high-roller"),
        Business("The Venetian", "https://www.venetian.com/"),
        Business("The Mob Museum", "https://themobmuseum.org/"),
        Business("Neon Museum", "https://www.neonmuseum.org/"),
        Business("Red Rock Canyon National Conservation Area", "https://www.redrockcanyonlv.org/"),
        Business("Luxor Sky Beam", "https://luxor.mgmresorts.com/en/meetings/luxor-sky-beam.html"),
        Business("Caesars Palace", "https://www.caesarspalace.com/"),
    ],
    ("Los Angeles", "itinerary"): [
        Business("Griffith Observatory", "https://www.griffithobservatory.org/"),
        Business("Hollywood Walk of Fame", "https://www.walkoffame.com/"),
        Business("Universal Studios Hollywood", "https://www.universalstudioshollywood.com/"),
        Business("Santa Monica Pier", "https://www.santamonicapier.org/"),
        Business("The Getty Center", "https://www.getty.edu/visit/center/"),
        Business("Los Angeles County Museum of Art (LACMA)", "https://www.lacma.org/"),
        Business("Disneyland Park", "https://disneyland.disney.go.com/"),
        Business("TCL Chinese Theatre", "https://www.tclchinesetheatres.com/"),
        Business("Rodeo Drive", "https://www.rodeodrive-bh.com/"),
        Business("Venice Beach", "https://www.venicebeach.com/"),
    ],
    ("Orlando", "itinerary"): [
        Business("Walt Disney World Resort", "https://www.disneyworld.com"),
        Business("Universal Studios Florida", "https://www.universalorlando.com"),
        Business("The Wizarding World of Harry Potter", "https://www.universalorlando.com/harry-potter"),
        Business("SeaWorld Orlando", "https://seaworld.com/orlando"),
        Business("Epcot", "https://disneyworld.disney.go.com/en-us/epcot/"),
        Business("Disney's Magic Kingdom", "https://www.disneyworld.com/magic-kingdom"),
        Business("Disney's Animal Kingdom", "https://www.disneyworld.com/animal-kingdom"),
        Business("LEGOLAND Florida", "https://www.legoland.com/florida/"),
        Business("Orlando Science Center", "https://www.osc.org"),
        Business("ICON Park", "https://iconparkorlando.com"),
    ],
    ("Chicago", "itinerary"): [
        Business("Millennium Park", "https://www.millenniumpark.org"),
        Business("Navy Pier", "https://navypier.org"),
        Business("The Art Institute of Chicago", "https://www.artic.edu"),
        Business("Willis Tower SkyDeck", "https://theskydeck.com"),
        Business("Field Museum", "https://www.fieldmuseum.org"),
        Business("Shedd Aquarium", "https://www.sheddaquarium.org"),
        Business("Lincoln Park Zoo", "https://www.lpzoo.org"),
        Business("Cloud Gate", "https://www.millenniumpark.org/parks-facilities/cloud-gate"),
        Business("The Magnificent Mile", "https://www.themagnificentmile.com"),
        Business("Chicago Riverwalk", "https://www.chicagoriverwalk.us"),
    ],
    ("San Francisco", "itinerary"): [
        Business("Golden Gate Bridge", "https://www.goldengatebridge.org/"),
        Business("Alcatraz Island", "https://www.nps.gov/alca/index.htm"),
        Business("Fisherman's Wharf", "https://www.fishermanswharf.org/"),
        Business("Chinatown", "https://www.sanfranciscochinatown.com/"),
        Business("Golden Gate Park", "https://goldengatepark.com/"),
        Business("Coit Tower", "https://sfrecpark.org/parks-open-spaces/coit-tower/"),
        Business("Lombard Street", "https://www.sfcityguides.org/public_guidelines/lombard.html"),
        Business("Palace of Fine Arts", "https://palaceoffinearts.org/"),
        Business("The Painted Ladies", "https://www.sfsymphony.org/"),
        Business("Exploratorium", "https://www.exploratorium.edu/"),
    ],
    ("Miami", "itinerary"): [
        Business("South Beach", "https://www.miamiandbeaches.com/things-to-do/beaches/south-beach"),
        Business("Vizcaya Museum and Gardens", "https://vizcaya.org/"),
        Business("Miami Seaquarium", "https://www.miamiseaquarium.com/"),
        Business("Wynwood Walls", "https://wynwoodwalls.com/"),
        Business("Little Havana", "https://www.thehavanaguide.com/"),
        Business("Bayside Marketplace", "https://baysidemarketplace.com/"),
        Business("Miami Design District", "https://www.miamidesigndistrict.net/"),
        Business("Fairchild Tropical Botanic Garden", "https://www.fairchildgarden.org/"),
        Business("Zoo Miami", "https://www.zoomiami.org/"),
        Business("American Airlines Arena", "https://www.aaarena.com/"),
    ],
    ("Washington", "itinerary"): [
        Business("National Mall and Memorial Parks", "https://www.nps.gov/nama/index.htm"),
        Business("Smithsonian National Museum of Natural History", "https://naturalhistory.si.edu/"),
        Business("Lincoln Memorial", "https://www.nps.gov/linc/index.htm"),
        Business("Smithsonian National Air and Space Museum", "https://airandspace.si.edu/"),
        Business("United States Capitol", "https://www.visitthecapitol.gov/"),
        Business("Washington Monument", "https://www.nps.gov/wamo/index.htm"),
        Business("White House", "https://www.whitehouse.gov/"),
        Business("National Gallery of Art", "https://www.nga.gov/"),
        Business("Vietnam Veterans Memorial", "https://www.nps.gov/vive/index.htm"),
        Business("National Museum of American History", "https://americanhistory.si.edu/"),
    ],
    ("New Orleans", "itinerary"): [
        Business("French Quarter", "https://www.frenchquarter.com"),
        Business("Jackson Square", "https://www.nola.gov/jackson-square"),
        Business("Bourbon Street", "https://www.nola.com/bourbon-street"),
        Business("St. Louis Cathedral", "https://www.stlouiscathedral.org"),
        Business("Garden District", "https://www.neworleans.com/places/garden-district"),
        Business("National WWII Museum", "https://www.nationalww2museum.org"),
        Business("Mardi Gras World", "https://www.mardigrasworld.com"),
        Business("Audubon Park", "https://www.audubon.org/parks/audubon-park"),
        Business("Louisiana State Museum", "https://www.louisianastatemuseum.org"),
        Business("City Park", "https://neworleanscitypark.com"),
    ],
    ("Nashville", "itinerary"): [
        Business("Country Music Hall of Fame and Museum", "https://countrymusichalloffame.org"),
        Business("Ryman Auditorium", "https://ryman.com"),
        Business("The Parthenon", "https://www.nashville.gov/departments/parks/parthenon"),
        Business("Johnny Cash Museum", "https://www.johnnycashmuseum.com"),
        Business("The Hermitage", "https://thehermitage.com"),
        Business("Nashville Zoo at Grassmere", "https://nashvillezoo.org"),
        Business("The Gaylord Opryland Resort & Convention Center", "https://www.gaylordhotels.com/en/gaylord-opryland.html"),
        Business("Music City Walk of Fame", "https://www.nashville.gov/departments/mcity/walk-of-fame"),
        Business("Cheekwood Estate & Gardens", "https://cheekwood.org"),
        Business("Frist Art Museum", "https://fristartmuseum.org"),
    ],
    ("New York", "personal injury"): [
        Business("Example Injury Law"),
        Business("Manhattan Accident Counsel"),
        Business("Five Borough Injury Group"),
        Business("Empire Trial Attorneys"),
        Business("NYC Injury Partners"),
        Business("Broadway Personal Injury Law"),
        Business("Metro Accident Advocates"),
        Business("Hudson Legal Group"),
    ],
}


def sample_businesses(city: str, practice_area: str, target_business: str) -> list[Business]:
    businesses = list(SAMPLE_COMPETITORS.get((city, practice_area), []))
    if not businesses:
        businesses = [
            Business(target_business),
            Business(f"{city} Legal Advocates"),
            Business(f"{city} Trial Group"),
            Business(f"{city} Justice Partners"),
            Business(f"{city} Counsel Group"),
            Business(f"Downtown {city} Attorneys"),
            Business(f"Metro {city} Law"),
            Business(f"{city} Client First Law"),
        ]
    if all(business.name != target_business for business in businesses):
        businesses.insert(0, Business(target_business))
    return businesses
